### ISSUE TITLE
Error launching

### ISSUE THREAD

**Issue by glberen** [vhp/terminal_velocity#1]
Hi, 

I'm getting an error trying to launch tv: terminal_velocity.notebook.NoteAlreadyExistsError: u'Note already in NoteBook: <file name>

How can I just clear out the existing dataset and have tv reindex the notes? I saw a sqlite notes file in my home directory, but moving that and relaunching didn't seem to affect anything. 

Thanks!

**Comment by glberen** [comment]
Actually, nevermind. I got this resolved. I had a couple of notes that were named the same, except that one had a space in it, which isn't exactly the same name, but whatever. Once I cleared that up, tv opened for me.

**Comment by vhp** [comment]
hey @glberen Thanks for the report. There was an issue which was recently patched that made it increasingly easy to get duplicate notes in your notebook. 

From the following line of code https://github.com/vhp/terminal_velocity/blob/master/terminal_velocity/notebook.py#L418-L422

`for note in self._notes:
            if note.title == title and note.extension == extension:
                raise NoteAlreadyExistsError(
                        u"Note already in NoteBook: {0}".format(note.title))
`

This is why tv was exiting. Just a protection mechanism so we know we are editing the correct note. Now as for why it found duplicates I'd have to know more about the situation. Glad to look into it if you could explain the conditions a bit more. 

Thanks for reporting.

**Comment by glberen** [comment]
It seems to be a particular set of files getting duplicated...although it's not a complete duplication. There's the added space and the fact that they are zero bytes in size. They have this format: logx_2016_07_01.txt. The dates differ, but the created files are logx_2016_07_01 .txt . A space is being added before the extension. I don't know if TV is doing this or some other program, however. The files reside on dropbox and there's likely a copy of nvALT running against the same dataset as well, but I haven't noticed the duplicated files till I started using tv.
