### ISSUE TITLE
Show default note directory flag

### ISSUE THREAD

**Issue by harrisonturton** [vhp/terminal_velocity#10]
Hi,

It'd be really nice to see where our notes are being stored. Something like 

```
$ terminal_velocity --dir
$ /home/user/.terminal_velocity/notes/
```

Would be super useful.

Cheers!

**Comment by vhp** [comment]
Thanks for the recommendation. I think using --dir will be confusing to 
people and would act as an override. If no override is given we could 
print it out but it's not really intuitive. I can't think of many 
programs that do that.

I'm not going to have the time to work on this one. But if you or 
anybody else feels strongly about it I'd happily take a PR. Maybe 
printing out all the settings would be a nice option. Thanks Harry.

**Comment by gwelr** [comment]
Isn't that already covered by the -p option? 

I have changed the default location in the .tvrc file and when i use the -p option, the notes_dir reports the new location and not the default one.

Or do I miss something ?

**Comment by vhp** [comment]
Yes the -p option will have in it where the notes are stored but it's 
not soley that information. My concern was that the --dir would be 
considered an override. We could do that as you can switch notes 
directories. Let me think on it.


For now you could make this an alias in your shell

  terminal_velocity -p | sed 's/\, /\n/g' | grep notes_dir
