### ISSUE TITLE
Crash when an single quote is added in note title

### ISSUE THREAD

**Issue by xird** [vhp/terminal_velocity#11]
To reproduce:
- Install terminal_velocity
- Launch terminal_velocity
- Type "Let's test this thing" and hit enter

Result: Stacktrace and "ValueError: No closing quotation"

**Comment by vhp** [comment]
Thanks a lot for reporting. What version are you using? This bug was 
recently fixed actually so I think updating to the newest would likely 
fix the issue. If not please let me know. Glad to look into it.

**Comment by xird** [comment]
I just did "pip install terminal_velocity".

**Comment by vhp** [comment]
Hey,

So this was fixed in a more recent PR but I haven't pushed the code to 
pypi yet. I'm going to try and fix a few more things and then push the 
new code.

**Comment by vhp** [comment]
New version should be out now
