### ISSUE TITLE
Integrated editor?

### ISSUE THREAD

**Issue by xird** [vhp/terminal_velocity#14]
I'm a Notational Velocity user, and one of the ways I often use the software is that I type in a search term in the input field, and then browse through the filtered list of notes with arrow keys. This is currently not possible with Terminal Velocity due to the fact that it uses an external editor to view and edit the notes.

Have you considered adding (an option to use) an integrated viewer/editor on the same display as the input field and the notes list? In other words, making it (optionally) more like NV?

**Comment by vhp** [comment]
Hi @xird This would be hard. Frankly I think if this is what you want I'd suggest you look for a NV alternative built in the editor of your choice. Actually there are ones build as plugins for many editors from vim, emacs to atom.
