### ISSUE TITLE
Optimize searching for large notes datasets

### ISSUE THREAD

**Issue by cipriancraciun** [vhp/terminal_velocity#17]
I have just tested `terminal_velocity` version `0.1.10` on my existing notes "dataset", which is composed of around 272 files, around ~120k lines in total, the majority of files being well under 200 lines and only a few being larger than 1k lines, and I've observed that the match-as-you-type behaviour of filtering the notes is quite sluggish.

My comparison "base" is running `rofi` (an X.org `dmenu` clone) and feeding it the contents of all those files.  And `rofi` in comparison seems quite snappy.

Hope it helps,
Ciprian.

**Comment by vhp** [comment]
Hi Ciprian,

This is a known problem with the design of terminal_velocity. The reason 
is everytime you search you loop through the documents in serial. Like a 
for loop. Unfortunately fixing this is going to take a major 
rearchitecture of the software. Atleast in that we implement another 
layer or use another tool to index.

I can certainly look into things further and see what can be done.
