### ISSUE TITLE
Vim-like keybinding

### ISSUE THREAD

**Issue by ka2o** [vhp/terminal_velocity#21]
It would be fantastic if we could have additional vim-like keybinding, i.e., going down in the list with ctrl+j and up in the list with ctrl+k.

**Comment by vhp** [comment]
HI @ka2o , I agree that it would be nice. But I don't have time to do it now. If you wanna take a shot at it feel free. I'm not exactly sure how to do it at the moment.

**Comment by Mooie** [comment]
Unfortunately, I lack the necessary skills. But +1 for this if you ever do find the time.
