### ISSUE TITLE
create a night mode color scheme

### ISSUE THREAD

**Issue by xcombelle** [vhp/terminal_velocity#7]
Hi I have a black terminal and the blue is unreadable. Is it possible to change the color scheme ?

**Comment by vhp** [comment]
Hi Xavier,

The colors are defined in the palette which is defined here 
https://github.com/vhp/terminal_velocity/blob/master/terminal_velocity/urwid_ui.py#L17

The urwid tutorial gives a bit of insight as to how it works. That can 
be found at http://urwid.org/tutorial/

Now as for why you can't see the "dark blue" setting. It could very well 
be a number of things. What terminal are you using and with what OS? I 
know I have certainly had problems like this when going over Putty where 
the colors are just atrocious.


Xavier Combelle wrote on 06/10/2017 06:00 AM:
