### ISSUE TITLE
shortcut path info in Wiki may need update

### ISSUE THREAD

**Issue by AnummaBrooke** [vhp/terminal_velocity#8]
First, thanks so much for this app!

In the Wiki here, for "How to Set a Keyboard Shortcut to Launch Terminal Velocity", the path is described as /usr/local/bin/terminal_velocity. However, on my computer using Ubuntu 16.04, I found that the correct path was /home/[username]/.local/bin/terminal_velocity.

Sorry if there is a proper way to recommend Wiki edits without opening an Issue.

Thanks again! I had despaired of finding an NValt replacement for the command line, but Terminal Velocity does everything I want. Sincerely,
Brooke

**Comment by vhp** [comment]
Hi,

I believe the issue is that it depends if it's a system wide install vs 
a local user install. The documentation is for when it's available to 
all. I really think the docs written originally were intended to just 
show the path to the executable but it could be anything.

**Comment by vhp** [comment]
Hey @AnummaBrooke I added some notes to the wiki. Let me know if this doesn't help at all. 

https://github.com/vhp/terminal_velocity/wiki/How-to-Set-a-Keyboard-Shortcut-to-Launch-Terminal-Velocity
